export const ENTITY_TYPES = {
  USER: "USER",
  USER_PROFILE: "USER_PROFILE",
  ORGANIZATION: "ORGANIZATION",
  ISSUE: "ISSUE",
  ISSUE_COMMENT: "ISSUE_COMMENT",
  PROJECT: "PROJECT",
  PROJECT_REQUEST: "PROJECT_REQUEST",
} as const;

export type EntityType = (typeof ENTITY_TYPES)[keyof typeof ENTITY_TYPES];
