export const ACTIVITY_TYPES = {
  USER_JOINED_ORG: "USER_JOINED_ORG",
  ORG_CREATED: "ORG_CREATED",
  ORG_DELETED: "ORG_DELETED",

  PROJECT_REQUEST_CREATED: "PROJECT_REQUEST_CREATED",
  PROJECT_REQUEST_APPROVED: "PROJECT_REQUEST_APPROVED",
  PROJECT_REQUEST_REJECTED: "PROJECT_REQUEST_REJECTED",

  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",

  ISSUE_CREATED: "ISSUE_CREATED",
  ISSUE_UPDATED: "ISSUE_UPDATED",
  ISSUE_STATUS_CHANGED: "ISSUE_STATUS_CHANGED",
  ISSUE_DELETED: "ISSUE_DELETED",

  ISSUE_COMMENT_CREATED: "ISSUE_COMMENT_CREATED",
  ISSUE_COMMENT_UPDATED: "ISSUE_COMMENT_UPDATED",
  ISSUE_COMMENT_DELETED: "ISSUE_COMMENT_DELETED",

  LABEL_ADDED: "LABEL_ADDED",
  LABEL_REMOVED: "LABEL_REMOVED",
} as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];
