import { softDeleteFilters } from "../filters/soft-delete.filter";
import { CARD_STATUS } from "@/common/constant/enums/card-status.enum";
import { Deck } from "./deck.entity";
import { GenerationJob } from "./generation-job.entity";
import { defineEntity, p } from "@mikro-orm/core";

/**
 * A single question/answer pair belonging to a deck.
 *
 * `generationJob` records provenance: which run produced this card, and
 * therefore which provider and model. That is deliberate — it is what lets
 * cards generated by an LLM be compared against cards from a future local
 * model, rather than mixing them indistinguishably.
 */
const FlashCardSchema = defineEntity({
  name: "FlashCard",
  tableName: "flash_card",
  properties: {
    id: p.uuid().primary().defaultRaw("gen_random_uuid()"),
    deck: () => p.manyToOne(Deck).joinColumn("deck_id").inversedBy("cards"),
    /** Null for hand-written cards; set for anything machine-generated. */
    generationJob: () =>
      p
        .manyToOne(GenerationJob)
        .joinColumn("generation_job_id")
        .inversedBy("cards")
        .nullable()
        .deleteRule("set null"),
    front: p.text(),
    back: p.text(),
    hint: p.text().nullable(),
    status: p
      .enum(() => CARD_STATUS)
      .nativeEnumName("card_status")
      .default(CARD_STATUS.DRAFT),
    /** Manual ordering within a deck; null means unordered. */
    position: p.integer().nullable(),
    deletedAt: p.datetime().fieldName("deleted_at").nullable(),
    createdAt: p
      .datetime()
      .fieldName("created_at")
      .onCreate(() => new Date()),
    updatedAt: p
      .datetime()
      .fieldName("updated_at")
      .onCreate(() => new Date())
      .onUpdate(() => new Date()),
  },
  filters: softDeleteFilters,
  indexes: [
    { properties: ["deck"] },
    { properties: ["status"] },
    { properties: ["deletedAt"] },
    // Cards are listed per deck; status filters study/quiz pools.
    { properties: ["deck", "status"] },
  ],
});

export class FlashCard extends FlashCardSchema.class {}
FlashCardSchema.setClass(FlashCard);
